// FETCH FAVOURITES
export const FETCH_FAVOURITE_REQUEST = 'FETCH_FAVOURITE_REQUEST'
export const FETCH_FAVOURITE_SUCCESS = 'FETCH_FAVOURITE_SUCCESS'
export const FETCH_FAVOURITE_ERROR = 'FETCH_FAVOURITE_ERROR'
