// TO FETCH A SINGLE BUSINESS
export const FETCH_BUSINESS_REQUEST = 'FETCH_BUSINESS_REQUEST'
export const FETCH_BUSINESS_SUCCESS = 'FETCH_BUSINESS_SUCCESS'
export const FETCH_BUSINESS_ERROR = 'FETCH_BUSINESS_ERROR'

// FETCH ALL BUSINESSES
export const FETCH_BUSINESSES_REQUEST = 'FETCH_BUSINESSES_REQUEST'
export const FETCH_BUSINESSES_SUCCESS = 'FETCH_BUSINESSES_SUCCESS'
export const FETCH_BUSINESSES_ERROR = 'FETCH_BUSINESSES_ERROR'

// FETCH BUSINESSES IN A PARTICULAR CATEGORY
