// TO FETCH A SINGLE BUSINESS
export const FETCH_BUSINESS_REQUEST = 'FETCH_BUSINESS_REQUEST'
export const FETCH_BUSINESS_SUCCESS = 'FETCH_BUSINESS_SUCCESS'
export const FETCH_BUSINESS_ERROR = 'FETCH_BUSINESS_ERROR'

// FETCH ALL BUSINESSES
export const FETCH_BUSINESSES_REQUEST = 'FETCH_BUSINESSES_REQUEST'
export const FETCH_BUSINESSES_SUCCESS = 'FETCH_BUSINESSES_SUCCESS'
export const FETCH_BUSINESSES_ERROR = 'FETCH_BUSINESSES_ERROR'

// FETCH GROCERY STORES
export const FETCH_GROCERY_STORES_REQUEST = 'FETCH_GROCERY_STORES_REQUEST'
export const FETCH_GROCERY_STORES_SUCCESS = 'FETCH_GROCERY_STORES_SUCCESS'
export const FETCH_GROCERY_STORES_ERROR = 'FETCH_GROCERY_STORES_ERROR'

// FETCH RESTAURANTS
export const FETCH_RESTAURANTS_REQUEST = 'FETCH_RESTAURANTS_REQUEST'
export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS'
export const FETCH_RESTAURANTS_ERROR = 'FETCH_RESTAURANTS_ERROR'

// FETCH SERIVCES
export const FETCH_SERIVCES_REQUEST = 'FETCH_SERIVCES_REQUEST'
export const FETCH_SERIVCES_SUCCESS = 'FETCH_SERIVCES_SUCCESS'
export const FETCH_SERIVCES_ERROR = 'FETCH_SERIVCES_ERROR'
